version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pqrs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pqrs
    ports:
      - "5432:5432"
    volumes:
      - pqrs_pgdata:/var/lib/postgresql/data

volumes:
  pqrs_pgdata:
